# Generated by Django 6.0.4 on 2026-04-17 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('attendance', models.FloatField()),
                ('communication_skill', models.IntegerField()),
                ('technical_skill', models.IntegerField()),
                ('aptitude_skill', models.IntegerField()),
                ('projects_count', models.IntegerField()),
                ('internships_count', models.IntegerField()),
                ('certifications_count', models.IntegerField()),
                ('resume_score', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=50)),
                ('probability', models.FloatField()),
                ('suggested_role', models.CharField(max_length=100)),
                ('missing_skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.studentprofile')),
            ],
        ),
    ]
